name: lkq-env
dependencies:
  # Core dependencies
  - python=3.7
  - tqdm
  - numpy
  # Visualization dependencies
  - jupyter
  - matplotlib
  # Dev dependencies
  - pytest
  - pip:
    - pytmx
    - pyscroll
    - pygame


